server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${P_MYSQL_URL}
    username: ${P_MYSQL_USERNAME}
    password: ${P_MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
      


