apiVersion: v1 
kind: Service
metadata: 
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080 
      nodePort: 30163
  type: NodePort 
---  
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hugojesusmr/employee:1.0
        ports:
        - containerPort: 8080 
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: host        
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: name                
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

